"""Build the open-vocabulary commodity lexicon used by the OOV eval probe.

Source: the Harmonized System nomenclature (HS 2022) as published by
https://github.com/datasets/harmonized-system — **ODC-PDDL-1.0 (public domain
dedication)**, derived from UN Comtrade. Free for commercial use.

Why this exists
---------------
The repo's own commodity pool is 589 hand-written strings. Measured against the
5,613 HS 6-digit subheadings, it matches 3.5% exactly and 13.3% even counting
shared head nouns — it has no representation of selenium, bulldozers, hearing
aids, photographic film, turbo-propellers. Any extractor evaluated on data built
from that pool is being tested on its own training vocabulary.

This module produces a vocabulary that is *disjoint by construction* from the
repo's pool, so the eval probe measures generalization rather than recall of a
memorized list. The output is committed so the probe is reproducible offline.

Usage:
    python -m scripts.build_hs_vocab                    # refresh from the network
    python -m scripts.build_hs_vocab --csv path/to.csv  # from a local copy
"""
from __future__ import annotations

import argparse
import csv
import io
import re
import sys
import urllib.request
from pathlib import Path

HS_CSV_URL = (
    "https://raw.githubusercontent.com/datasets/harmonized-system/master/"
    "data/harmonized-system.csv"
)
DEFAULT_OUT = Path(__file__).resolve().parent.parent / "ner" / "commodity" / "resources"

# HS descriptions carry catch-all and structural entries that are not commodity
# surface forms anyone would write on a manifest.
_SKIP_PREFIXES = (
    "other", "parts", "n.e.c", "not elsewhere", "of a kind", "and parts",
)
_SKIP_TOKENS = re.compile(r"\b(?:n\.e\.c|nes|excluding|including)\b", re.IGNORECASE)


def fetch_csv(url: str = HS_CSV_URL) -> str:
    with urllib.request.urlopen(url, timeout=60) as resp:
        return resp.read().decode("utf-8")


def _clean(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip(" ;,.")


def _is_usable(phrase: str) -> bool:
    if not phrase or len(phrase) < 3:
        return False
    low = phrase.lower()
    if low.startswith(_SKIP_PREFIXES):
        return False
    if _SKIP_TOKENS.search(low):
        return False
    # Needs at least one alphabetic run; skip pure numerics / codes.
    return bool(re.search(r"[a-z]{3,}", low))


def extract_vocab(csv_text: str) -> tuple[list[str], list[str]]:
    """Return (heads, descriptions).

    `heads` are short surface forms ("selenium", "umbrellas") — how a commodity is
    named in a terse manifest line. `descriptions` keep HS's fuller phrasing
    ("coffee; roasted, not decaffeinated") — how it appears in a customs-style
    long-form entry. Both registers matter: span *extent* was the dominant error
    mode in earlier measurement, and long descriptions are where it shows up.
    """
    rows = list(csv.DictReader(io.StringIO(csv_text)))
    heads: dict[str, None] = {}
    descriptions: dict[str, None] = {}

    for row in rows:
        if row.get("level") not in {"4", "6"}:
            continue
        raw = _clean(row.get("description", ""))
        if not raw:
            continue

        full = _clean(raw.replace(";", ","))
        if _is_usable(full) and len(full) <= 90:
            descriptions.setdefault(full, None)

        head = _clean(re.split(r"[;,]", raw)[0])
        if _is_usable(head) and len(head) <= 45:
            heads.setdefault(head.lower(), None)

    return sorted(heads), sorted(descriptions)


_HEADER = """\
# Harmonized System commodity vocabulary (HS 2022).
# Source: https://github.com/datasets/harmonized-system  (ODC-PDDL-1.0, public domain)
# Generated by `python -m scripts.build_hs_vocab` — do not edit by hand.
#
# Used ONLY to build the open-vocabulary eval probe. Never used as a matcher:
# measured directly, dictionary-matching these phrases scored 0.135 F1, and
# adding them to a working gazetteer dropped it from 0.716 to 0.650.
"""


def write_vocab(out_dir: Path, heads: list[str], descriptions: list[str]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, values in (("hs_heads.txt", heads), ("hs_descriptions.txt", descriptions)):
        path = out_dir / name
        path.write_text(_HEADER + "\n".join(values) + "\n", encoding="utf-8")
        print(f"  wrote {path.relative_to(out_dir.parent.parent.parent)} ({len(values)} entries)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", type=Path, help="local harmonized-system.csv (skips download)")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="output resource dir")
    args = parser.parse_args()

    if args.csv:
        csv_text = args.csv.read_text(encoding="utf-8")
    else:
        print(f"fetching {HS_CSV_URL}")
        try:
            csv_text = fetch_csv()
        except OSError as exc:  # pragma: no cover - network dependent
            print(f"ERROR: could not fetch HS data: {exc}", file=sys.stderr)
            print("Pass --csv with a local copy instead.", file=sys.stderr)
            sys.exit(2)

    heads, descriptions = extract_vocab(csv_text)
    if not heads or not descriptions:
        print("ERROR: extracted an empty vocabulary", file=sys.stderr)
        sys.exit(1)
    write_vocab(args.out, heads, descriptions)


if __name__ == "__main__":
    main()
