"""
ORG entity pool for synthetic NER training-data seed generation.

Coverage follows the data specification:
  - §4.2   ORG span boundary rules (include legal suffix when contiguous,
           acronyms standalone valid, suffix-less names valid)
  - §4.7   ORG legal-entity suffixes by jurisdiction (~55-row table):
           USA, UK, Ireland, Germany, Austria, Switzerland, France,
           Belgium/Luxembourg, Netherlands, Spain, Portugal, Italy,
           Sweden, Norway, Denmark, Finland, Iceland, Poland,
           Czech/Slovakia, Hungary, Romania, Greece, Russia, Ukraine,
           Turkey, Israel, Saudi Arabia, UAE, Egypt, Morocco/Algeria/Tunisia,
           Nigeria, Kenya, South Africa, Ghana, China, Hong Kong, Taiwan,
           Japan, South Korea, Singapore, Malaysia, Indonesia, Philippines,
           Thailand, Vietnam, India, Pakistan, Sri Lanka, Bangladesh,
           Brazil, Mexico, Argentina, Chile, Colombia, Peru, Venezuela,
           Canada, Australia, New Zealand
  - §4.8   BRAND naming patterns: single-token casing, multi-word (hyphenated,
           ampersand, slash, apostrophe, quoted, exclamation, special chars,
           "The" prefix, possessive), numbered brands, non-ASCII/diacritics,
           brand portfolios/sub-brands, brand-as-modifier context
  - §4.9   ORG/BRAND fuzzy & messy variants: casing drift, suffix punctuation
           drift, whitespace/separator drift, apostrophe variants,
           abbreviation/acronym, brand-vs-legal, OCR corruption,
           romanization pairs, subsidiary/branch, JV/DBA, state-owned,
           bilingual/dual-script
  - §11.4  ORG diversity: global multinationals, regional traders, SMEs,
           government/state-owned entities

Each string is the EXACT gold span text. Apostrophes in names use
double-quoted Python string literals. No imports, no SQL.
"""

ORGS: list[str] = [

    # ── §4.7 USA — Inc. / Corp. / LLC / LLP / PC / Holdings ─────────────────
    "Acme Trading Co.",
    "Riverside Manufacturing Inc.",
    "Golden Gate Holdings Corp.",
    "Summit Logistics LLC",
    "Pacific Rim Partners LLP",
    "Coastal Advisors PC",
    "Westfield Capital Management L.L.C.",
    "Northpoint Trading PLLC",
    "Delta Resources LP",
    "Cornerstone Legal PA",
    "BlueSky Ventures Inc.",
    "Redwood Timber Corporation",
    "Horizon Energy Holdings",
    "Pinnacle Freight Inc.",
    "Atlas Commodities Corp.",

    # ── §4.7 UK — Ltd / PLC / LLP / & Co. / Holdings ─────────────────────────
    "Hartfield & Sons Ltd",
    "Whitmore Industries PLC",
    "Morrison & Clarke LLP",
    "Pemberton Holdings Limited",
    "Aldgate Shipping plc",
    "Fenwick & Co.",
    "Blackwood Estates Ltd",
    "Castlebridge Freight Holdings",
    "Greystone Capital plc",
    "Northumbria Steel Ltd",

    # ── §4.7 Ireland — Ltd / DAC / CLG / PLC / Teoranta ──────────────────────
    "Shamrock Exports Ltd",
    "CelticBridge Finance DAC",
    "Dublin Harbour CLG",
    "Kerry Agribusiness PLC",
    "Connacht Iompair Teoranta",

    # ── §4.7 Germany — GmbH / AG / KG / KGaA / OHG / SE / Stiftung / gGmbH / UG ──
    "Nordwind Logistics GmbH",
    "Berliner Handels AG",
    "Rheinmetall KG",
    "Thyssen & Partner KGaA",
    "Frankfurter Spediteure OHG",
    "Siemens SE",
    "Heinrich-Böll-Stiftung",
    "GreenFuture gGmbH",
    "Quickstart Solutions UG (haftungsbeschränkt)",
    "Bayerische Metallwerke GmbH",

    # ── §4.7 Austria — GmbH / AG / KG / OG / GesmbH ─────────────────────────
    "Wiener Handelshaus GmbH",
    "Alpenlogistik AG",
    "Steyr Transport KG",
    "Donau Schifffahrt OG",
    "Salzburger Rohstoffe GesmbH",

    # ── §4.7 Switzerland — AG / SA / Sàrl / GmbH / Genossenschaft ────────────
    "Zurich Commodity Traders AG",
    "Genève Commerce SA",
    "Lugano Finance Sàrl",
    "Berner Handwerk GmbH",
    "Migros Genossenschaft",

    # ── §4.7 France — SA / SAS / SARL / SCA / SCS / EURL / SNC / SCEA / SCP ─
    "Compagnie Maritime de France SA",
    "Bordeaux Négoce SAS",
    "Provence Distribution SARL",
    "Alsace Vins SCA",
    "Loire Trading SCS",
    "Dupont Conseil EURL",
    "Normandie Bois SNC",
    "Château Margaux SCEA",
    "Cabinet Lefebvre SCP",
    "Paris Commodities SA",

    # ── §4.7 Belgium / Luxembourg — SA / SPRL / BVBA / CVBA / SCRL / NV / BV ─
    "Bruxelles Négoce SA",
    "Anvers Transport SPRL",
    "Ghent Industries BVBA",
    "Liège Cooperative CVBA",
    "Lux Trade SCRL",
    "ArcelorMittal NV",
    "Belgo Logistics BV",

    # ── §4.7 Netherlands — BV / NV / CV / Coöperatie / Stichting ─────────────
    "Rotterdam Freight BV",
    "Amsterdam Holdings NV",
    "Utrecht Handel CV",
    "FrieslandCampina Coöperatie",
    "Stichting Harbour Trust",
    "Schiphol Cargo BV",

    # ── §4.7 Spain — S.A. / SA / S.L. / SL / SLU / Sdad. Coop. ──────────────
    "Iberica Commodities S.A.",
    "Mercado Global SA",
    "Distribuciones del Sur S.L.",
    "Valencia Export SL",
    "Malaga Soluciones SLU",
    "Cooperativa Agrícola Sdad. Coop.",

    # ── §4.7 Portugal — SA / Lda. / Sociedade Unipessoal ─────────────────────
    "Porto Comércio SA",
    "Lisboa Transitários Lda.",
    "Faro Imóveis Sociedade Unipessoal",

    # ── §4.7 Italy — S.p.A. / S.r.l. / S.a.s. / S.n.c. / S.c.a.r.l. ────────
    "Fiat Industrial S.p.A.",
    "Venezia Commercio S.r.l.",
    "Romano & Figli S.a.s.",
    "Napoli Tessile S.n.c.",
    "Consorzio Meridionale S.c.a.r.l.",
    "Generali Assicurazioni S.p.A.",

    # ── §4.7 Sweden — AB / HB / KB / ekonomisk förening ──────────────────────
    "Volvo Group AB",
    "Norrköping Handels HB",
    "Malmö Rederi KB",
    "Lantbrukarnas ekonomisk förening",
    "Ericsson AB",

    # ── §4.7 Norway — AS / ASA / ANS / DA / BA ───────────────────────────────
    "Statoil AS",
    "Norsk Hydro ASA",
    "Bergen Shipping ANS",
    "Tromsø Fiskeri DA",
    "Norges Bondelag BA",

    # ── §4.7 Denmark — A/S / ApS / K/S / I/S / P/S ──────────────────────────
    "Maersk A/S",
    "Copenhagen Ventures ApS",
    "Nordic Capital K/S",
    "Aarhus Grain I/S",
    "Danish Shipping P/S",

    # ── §4.7 Finland — Oy / Oyj / Ky / Tmi / Osk ────────────────────────────
    "Kesko Oy",
    "Nokia Oyj",
    "Tampereen Kuljetus Ky",
    "Mäkinen Tmi",
    "Vaasan Osuuskunta Osk",

    # ── §4.7 Iceland — ehf. / hf. / slhf. / sf. ─────────────────────────────
    "Reykjavik Shipping ehf.",
    "Islandsbanki hf.",
    "Nordur sf.",
    "Hafnarfjördur slhf.",

    # ── §4.7 Poland — Sp. z o.o. / S.A. / Sp. j. / S.K.A. ──────────────────
    "Polska Żegluga Sp. z o.o.",
    "PKN Orlen S.A.",
    "Kowalski & Nowak Sp. j.",
    "Gdańsk Investments S.K.A.",
    "Warsaw Logistics Sp. z o.o.",

    # ── §4.7 Czech / Slovakia — s.r.o. / a.s. / k.s. / v.o.s. ──────────────
    "Praha Obchod s.r.o.",
    "ČEZ a.s.",
    "Bratislava Finance k.s.",
    "Brno Partneři v.o.s.",

    # ── §4.7 Hungary — Kft. / Zrt. / Nyrt. / Bt. / Kkt. ─────────────────────
    "Budapest Kereskedő Kft.",
    "OTP Bank Nyrt.",
    "Magyar Energetika Zrt.",
    "Pécs Fuvar Bt.",
    "Debreceni Kkt.",

    # ── §4.7 Romania — SRL / SA / SCS / SCA / PFA ────────────────────────────
    "Bucharest Trade SRL",
    "Petrom SA",
    "Ploiești Comerț SCS",
    "Cluj Investiții SCA",
    "Ionescu Consulting PFA",

    # ── §4.7 Greece — AE / EPE / OE / EE / IKE ───────────────────────────────
    "Athen Shipping AE",
    "Piraeus Trade EPE",
    "Thessaloniki Partners OE",
    "Patras Commerce EE",
    "Heraklion Ventures IKE",

    # ── §4.7 Russia — OOO / OAO / PAO / ZAO / IP / AO ───────────────────────
    "Роснефть ОАО",
    "Газпром ПАО",
    "Лукойл ПАО",
    "Московский Торговый Дом ООО",
    "Сбербанк АО",
    "Nornickel PAO",
    "Severstal OAO",
    "Magnit ZAO",
    "Petrov IP",

    # ── §4.7 Ukraine — TOV / PrAT / PAT / FOP ───────────────────────────────
    "Kyiv Grain TOV",
    "Metinvest PrAT",
    "Ukrgazbank PAT",
    "Bondarenko FOP",

    # ── §4.7 Turkey — A.Ş. / Ltd. Şti. ──────────────────────────────────────
    "Koç Holding A.Ş.",
    "Türk Telekomünikasyon A.Ş.",
    "Anadolu Ticaret Ltd. Şti.",
    "İstanbul Lojistik A.Ş.",
    "Ankara Tekstil Ltd. Şti.",

    # ── §4.7 Israel — Ltd / Bet"M / R.A. / Aguda ─────────────────────────────
    "Tel Aviv Trading Ltd",
    "Jerusalem Ventures Bet\"M",
    "Haifa Exports R.A.",
    "Kibbutz Commerce Aguda",

    # ── §4.7 Saudi Arabia — Co. Ltd. / LLC / JSC ─────────────────────────────
    "Saudi Arabian Oil Company",
    "Al-Rajhi Trading Co. Ltd.",
    "Riyadh Commerce LLC",
    "Saudi Telecom Company JSC",

    # ── §4.7 UAE — LLC / FZE / FZ-LLC / DMCC / JLT / PJSC ───────────────────
    "Emirates Global Traders LLC",
    "Dubai Commodities FZE",
    "Sharjah Imports FZ-LLC",
    "Gems International DMCC",
    "Arabian Gulf Trade JLT",
    "Emirates NBD PJSC",
    "Abu Dhabi National Energy Company PJSC",

    # ── §4.7 Egypt — S.A.E. / LLC / Joint Stock Co. ──────────────────────────
    "Cairo Trading S.A.E.",
    "Alexandria Shipping LLC",
    "Egyptian Petrochemicals Joint Stock Co.",

    # ── §4.7 Morocco / Algeria / Tunisia — SA / SARL / SCA ───────────────────
    "Casablanca Négoce SA",
    "Algérie Commerce SARL",
    "Tunis Industrie SCA",

    # ── §4.7 Nigeria — Plc / Ltd / Co. Ltd. ──────────────────────────────────
    "Dangote Cement Plc",
    "Lagos Freight Ltd",
    "Abuja Trading Co. Ltd.",

    # ── §4.7 Kenya — Ltd / Limited / Plc / Co. ───────────────────────────────
    "Nairobi Exports Ltd",
    "East Africa Breweries Limited",
    "Kenya Power Plc",
    "Mombasa Traders Co.",

    # ── §4.7 South Africa — Pty Ltd / (Pty) Ltd / Proprietary Limited / CC ───
    "Johannesburg Commodities Pty Ltd",
    "Cape Town Mining (Pty) Ltd",
    "Pretoria Resources Proprietary Limited",
    "Durban Traders Ltd",
    "Bloemfontein Ventures CC",
    "Anglo American Plc",

    # ── §4.7 Ghana — Ltd / Plc / Co. Ltd. ────────────────────────────────────
    "Accra Exports Ltd",
    "Ghana Gold Plc",
    "Kumasi Trading Co. Ltd.",

    # ── §4.7 China (mainland) — Co., Ltd. / 有限公司 / 集团 / 控股 ────────────
    "Huawei Technologies Co., Ltd.",
    "Beijing Commerce Co., Ltd.",
    "中国石化有限公司",
    "COSCO Shipping Holdings",
    "中国移动通信集团",
    "Alibaba Group Holding Limited",
    "BYD Co., Ltd.",
    "Sinopec Corp.",
    "China Resources 华润控股",

    # ── §4.7 Hong Kong — Ltd / Limited / Co. Ltd. / (HK) ─────────────────────
    "Hutchison Whampoa Limited",
    "Li & Fung Ltd",
    "Pacific Basin Shipping (HK)",
    "Wing Lung Bank Co. Ltd.",
    "Swire Pacific Limited",

    # ── §4.7 Taiwan — Co., Ltd. / Inc. / 股份有限公司 ────────────────────────
    "TSMC Co., Ltd.",
    "Foxconn Technology Inc.",
    "Formosa Plastics股份有限公司",
    "MediaTek Inc.",

    # ── §4.7 Japan — K.K. / Co., Ltd. / Inc. / Y.K. / G.K. ─────────────────
    "Toyota Motor Corporation K.K.",
    "Mitsubishi Corporation Co., Ltd.",
    "Sony Group Inc.",
    "Yamaha Motor Y.K.",
    "SoftBank G.K.",
    "Sumitomo Mitsui Banking Corporation",
    "Nippon Steel Co., Ltd.",

    # ── §4.7 South Korea — Co., Ltd. / Inc. / Corp. / 주식회사 ──────────────
    "Samsung Electronics Co., Ltd.",
    "Hyundai Motor Company",
    "LG Electronics Corp.",
    "SK Hynix Inc.",
    "POSCO Corp.",
    "삼성물산 주식회사",
    "Lotte Corporation",

    # ── §4.7 Singapore — Pte Ltd / Pte. Ltd. / Limited / Pte / LLP ──────────
    "Acme Trading (Singapore) Pte. Ltd.",
    "Temasek Holdings Pte Ltd",
    "Singapore Airlines Limited",
    "DBS Bank Pte",
    "Raffles Medical Group LLP",
    "Olam International Pte. Ltd.",

    # ── §4.7 Malaysia — Sdn. Bhd. / Sdn Bhd / Berhad / Bhd. / PLT ───────────
    "Petronas Chemicals Sdn. Bhd.",
    "Maybank Berhad",
    "Top Glove Bhd.",
    "Kuala Lumpur Trading Sdn Bhd",
    "Tenaga Nasional Berhad",
    "Affin Hwang PLT",

    # ── §4.7 Indonesia — PT / PT. / Tbk / Persero / CV ───────────────────────
    "PT Pertamina Persero",
    "PT Indofood Sukses Makmur Tbk",
    "PT. Astra International",
    "Gudang Garam Tbk",
    "CV Maju Bersama",

    # ── §4.7 Philippines — Inc. / Corp. / Corporation / Ltd. ─────────────────
    "Jollibee Foods Corporation",
    "San Miguel Corp.",
    "Ayala Land Inc.",
    "PLDT Inc.",
    "BDO Unibank Ltd.",

    # ── §4.7 Thailand — Co., Ltd. / PCL / บริษัท ... จำกัด ──────────────────
    "PTT Public Company PCL",
    "Charoen Pokphand Foods Co., Ltd.",
    "Kasikornbank PCL",
    "บริษัท ไทยออยล์ จำกัด",

    # ── §4.7 Vietnam — Ltd. / JSC / Co., Ltd. ────────────────────────────────
    "Vietnam Dairy Products JSC",
    "PetroVietnam Co., Ltd.",
    "Masan Group Ltd.",
    "Hoa Phat Steel Co., Ltd.",

    # ── §4.7 India — Pvt. Ltd. / Pvt Ltd / Private Limited / Ltd / LLP ───────
    "Reliance Industries Limited",
    "Tata Consultancy Services Ltd",
    "Infosys Private Limited",
    "Wipro Pvt. Ltd.",
    "Mahindra & Mahindra Pvt Ltd",
    "HDFC Bank Ltd",
    "Adani Ports LLP",
    "Bharat Heavy Electricals Limited",
    "Bajaj Auto Ltd",

    # ── §4.7 Pakistan — Pvt. Ltd. / (Pvt) Limited / Ltd / (SMC-Pvt) Ltd. ─────
    "Pakistan Petroleum Pvt. Ltd.",
    "Habib Bank (Pvt) Limited",
    "Engro Corporation Ltd",
    "Lucky Cement (SMC-Pvt) Ltd.",

    # ── §4.7 Sri Lanka — PLC / Ltd / (Pvt) Ltd ───────────────────────────────
    "Hemas Holdings PLC",
    "Ceylon Tea Services Ltd",
    "Sri Lanka Telecom (Pvt) Ltd",

    # ── §4.7 Bangladesh — Ltd. / Limited / (Pvt.) Ltd. / Group ──────────────
    "BRAC Bank Ltd.",
    "Grameenphone Limited",
    "Square Pharmaceuticals (Pvt.) Ltd.",
    "Bashundhara Group",

    # ── §4.7 Brazil — Ltda. / S.A. / S/A / EIRELI / ME / EPP ────────────────
    "Petróleo Brasileiro S.A.",
    "Vale S.A.",
    "Embraer S/A",
    "Distribuidora Nordeste Ltda.",
    "Construções Silva EIRELI",
    "Padaria Santos ME",
    "TechStart Brasil EPP",
    "Itaú Unibanco S.A.",

    # ── §4.7 Mexico — S.A. / S.A. de C.V. / S. de R.L. de C.V. / S.A.B. de C.V. ─
    "FEMSA S.A.B. de C.V.",
    "América Móvil S.A.B. de C.V.",
    "Cemex S.A. de C.V.",
    "Comercial Mexicana S. de R.L. de C.V.",
    "Grupo Bimbo S.A.",
    "Gruma S.A.B. de C.V.",

    # ── §4.7 Argentina — S.A. / SRL / SAS / Coop. Ltda. ─────────────────────
    "YPF S.A.",
    "Mercado Libre SRL",
    "Pampa Energía SAS",
    "Cooperativa Agropecuaria Coop. Ltda.",

    # ── §4.7 Chile — S.A. / Ltda. / SpA / EIRL ───────────────────────────────
    "Codelco S.A.",
    "Falabella Ltda.",
    "Entel SpA",
    "Minera Los Andes EIRL",

    # ── §4.7 Colombia — S.A. / S.A.S. / Ltda. ────────────────────────────────
    "Ecopetrol S.A.",
    "Grupo Éxito S.A.S.",
    "Avianca Ltda.",

    # ── §4.7 Peru — S.A. / S.A.C. / S.R.L. / E.I.R.L. ───────────────────────
    "Southern Copper S.A.",
    "Intercorp Perú S.A.C.",
    "Lima Transportes S.R.L.",
    "Artesanías del Sur E.I.R.L.",

    # ── §4.7 Venezuela — C.A. / S.A. / S.R.L. ───────────────────────────────
    "PDVSA C.A.",
    "Empresas Polar S.A.",
    "Caracas Importaciones S.R.L.",

    # ── §4.7 Canada — Inc. / Ltd. / Corp. / ULC / LLP / Ltée ────────────────
    "Royal Bank of Canada Corp.",
    "Bombardier Inc.",
    "Shopify Ltd.",
    "SNC-Lavalin ULC",
    "McCarthy Tétrault LLP",
    "Banque Nationale Ltée",

    # ── §4.7 Australia — Pty Ltd / Pty. Ltd. / Limited / Ltd / Pty. ──────────
    "BHP Group Pty Ltd",
    "Woolworths Limited",
    "Wesfarmers Ltd",
    "Rio Tinto Pty. Ltd.",
    "Macquarie Group Pty.",

    # ── §4.7 New Zealand — Ltd / Limited ─────────────────────────────────────
    "Fonterra Co-operative Group Limited",
    "Air New Zealand Ltd",

    # ── §4.8 Single-token brands — All-caps ──────────────────────────────────
    "IBM",
    "IKEA",
    "BMW",
    "HSBC",
    "KFC",
    "ASML",
    "BASF",
    "BBVA",
    "LG",
    "UNIQLO",
    "KPMG",
    "BP",
    "BHP",
    "ABB",
    "UPS",
    "DHL",
    "TNT",
    "SAP",
    "AWS",
    "CNN",
    "BBC",
    "IMF",
    "WHO",
    "WTO",
    "NATO",
    "OPEC",
    "STC",
    "JSW",
    "TCS",
    "ONGC",
    "BHEL",
    "KEPCO",
    "CNPC",
    "ICBC",
    "CNOOC",
    "POSCO",
    "KIA",
    "RIL",
    "EDF",
    "ENI",
    "BNP",
    "AXA",
    "PWC",

    # ── §4.8 Single-token brands — CamelCase ─────────────────────────────────
    "PayPal",
    "FedEx",
    "YouTube",
    "GitHub",
    "LinkedIn",
    "OpenAI",
    "EasyJet",
    "JetBlue",
    "MasterCard",
    "MetLife",
    "WeChat",
    "AirBnb",
    "DoorDash",
    "Instacart",
    "GrubHub",
    "SpaceX",
    "SolarEdge",
    "MindTree",
    "HubSpot",
    "DocuSign",
    "CloudFlare",
    "ByteDance",
    "TikTok",
    "SnapChat",
    "WhatsApp",
    "Instagram",
    "Pinterest",
    "Reddit",
    "Discord",

    # ── §4.8 Single-token brands — lowercase-by-design / initial-lower CamelCase
    "eBay",
    "iPhone",
    "iPad",
    "iPod",
    "mRNA",
    "iCloud",

    # ── §4.8 Single-token brands — vowel-light marketing ─────────────────────
    "Lyft",
    "Tumblr",
    "Flickr",
    "Grindr",
    "Rappi",
    "Fiverr",
    "Scribd",

    # ── §4.8 Multi-word — Hyphenated ─────────────────────────────────────────
    "Coca-Cola",
    "Bristol-Myers Squibb",
    "Häagen-Dazs",
    "Mercedes-Benz",
    "Hewlett-Packard",
    "Wal-Mart",
    "BNP Paribas",
    "Renault-Nissan-Mitsubishi Alliance",
    "BP-Rosneft JV",
    "Baker-Hughes",
    "Booz-Allen Hamilton",
    "Smith-Midland Corporation",
    "Lloyd's",

    # ── §4.8 Multi-word — Ampersand ──────────────────────────────────────────
    "Procter & Gamble",
    "Johnson & Johnson",
    "Marks & Spencer",
    "Dolce & Gabbana",
    "H&M",
    "AT&T",
    "A&W",
    "Ben & Jerry's",
    "Ernst & Young",
    "Deloitte & Touche",
    "Merrill Lynch & Co.",
    "Tiffany & Co.",
    "Marsh & McLennan",
    "Baker & McKenzie",
    "Allen & Overy",
    "Linklaters & Alliance",
    "B&Q",
    "Bed Bath & Beyond",
    "Simon & Schuster",

    # ── §4.8 Multi-word — Slash ───────────────────────────────────────────────
    "B/E Aerospace",
    "S/MIME Solutions",
    "OS/2 Systems",

    # ── §4.8 Multi-word — Apostrophe (double-quoted strings) ─────────────────
    "McDonald's",
    "Wendy's",
    "Macy's",
    "Sotheby's",
    "Levi's",
    "Hershey's",
    "Reese's",
    "Domino's",
    "Denny's",
    "Arby's",
    "Trader Joe's",
    "Dave's Killer Bread",
    "OBrien & Co.",

    # ── §4.8 Multi-word — Quoted / Special chars ─────────────────────────────
    'Toys "R" Us',
    'Books "A" Million',
    "E*TRADE",
    "Yahoo!",
    "Asahi+",

    # ── §4.8 Multi-word — "The" prefix ───────────────────────────────────────
    "The North Face",
    "The Home Depot",
    "The Coca-Cola Company",
    "The Boeing Company",
    "The Walt Disney Company",
    "The Hershey Company",
    "The Goldman Sachs Group",

    # ── §4.8 Numbered brands ─────────────────────────────────────────────────
    "3M",
    "7-Eleven",
    "7-Up",
    "21st Century Fox",
    "Forever 21",
    "Heinz 57",
    "99 Cents Only",
    "5 Guys",
    "A1",
    "J2 Communications",
    "Channel 4",
    "Studio 54",

    # ── §4.8 Non-ASCII / diacritics — French ─────────────────────────────────
    "L'Oréal",
    "Nestlé",
    "Citroën",
    "Renault",
    "Carrefour",
    "Crédit Agricole",
    "Société Générale",
    "BNP Paribas S.A.",
    "Peugeot",
    "Michelin",
    "Moët & Chandon",
    "Hermès",
    "Cartier",
    "Chanel",

    # ── §4.8 Non-ASCII / diacritics — Spanish ────────────────────────────────
    "Telefónica",
    "Inditex",
    "Iberdrola",
    "Banco Santander",
    "Endesa",
    "Mapfre",

    # ── §4.8 Non-ASCII / diacritics — German ─────────────────────────────────
    "Müller",
    "Lufthansa",
    "Bayer",
    "Henkel",
    "Beiersdorf",
    "Volkswagen",
    "Daimler AG",
    "Allianz",
    "Deutsche Bank AG",
    "Bosch",
    "Würth",
    "Märklin",

    # ── §4.8 Non-ASCII / diacritics — Scandinavian ───────────────────────────
    "LEGO",
    "Volvo",
    "Ericsson",
    "Spotify",
    "Ørsted",
    "Equinor",
    "Telenor",
    "H&M Hennes & Mauritz AB",
    "Electrolux",
    "SSAB",

    # ── §4.8 Non-ASCII — Japanese romanized ──────────────────────────────────
    "Asahi",
    "Kirin",
    "Sapporo",
    "Toyota",
    "Honda",
    "Mitsubishi",
    "Sumitomo",
    "Canon",
    "Panasonic",
    "Hitachi",
    "Fujitsu",
    "Ricoh",
    "Nikon",
    "Bridgestone",

    # ── §4.8 Non-ASCII — Japanese script ─────────────────────────────────────
    "トヨタ",
    "三菱",
    "日立",
    "ソニー",
    "東芝",

    # ── §4.8 Non-ASCII — Mandarin pinyin ─────────────────────────────────────
    "Huawei",
    "Xiaomi",
    "Lenovo",
    "BYD",
    "Geely",
    "Haier",
    "Alibaba",
    "Tencent",
    "Baidu",
    "JD.com",
    "Meituan",
    "Pinduoduo",
    "CATL",
    "Sinopec",

    # ── §4.8 Non-ASCII — Chinese script ──────────────────────────────────────
    "华为",
    "工商银行",
    "中国移动",
    "中国石化",
    "比亚迪",

    # ── §4.8 Non-ASCII — Korean ──────────────────────────────────────────────
    "Samsung",
    "Hyundai",
    "SK Hynix",
    "Kia",
    "삼성",
    "현대자동차",

    # ── §4.8 Non-ASCII — Cyrillic ────────────────────────────────────────────
    "Газпром",
    "Лукойл",
    "Сбербанк",
    "Яндекс",
    "Роснефть",

    # ── §4.8 Non-ASCII — Arabic transliteration ──────────────────────────────
    "Aramco",
    "Emirates",
    "Etihad",
    "Al-Futtaim",
    "Al-Rajhi",
    "Saudi Telecom",
    "Qatar Airways",
    "Qatar Petroleum",
    "Masraf Al Rayan",

    # ── §4.8 Non-ASCII — Indian ───────────────────────────────────────────────
    "Tata",
    "Reliance",
    "Infosys",
    "Wipro",
    "Mahindra",
    "Bharti Airtel",
    "Adani",
    "HCL Technologies",
    "Tech Mahindra",

    # ── §4.8 Brand portfolios / sub-brands as ORG ─────────────────────────────
    "Tide",
    "Pampers",
    "Gillette",
    "Olay",
    "Crest",
    "Bounty",
    "Pantene",
    "Vicks",
    "Dove",
    "Knorr",
    "Lipton",
    "Axe",
    "Surf",
    "Lux",
    "Magnum",
    "Pepsi",
    "Lay's",
    "Doritos",
    "Quaker",
    "Gatorade",
    "Tropicana",
    "Mountain Dew",
    "Nescafé",
    "KitKat",
    "Maggi",
    "Perrier",
    "Purina",
    "Gerber",
    "Tata Steel",
    "Tata Motors",
    "Jaguar Land Rover",
    "Tata Consumer Products",
    "Samsung Electronics",
    "Samsung C&T",
    "Samsung Heavy Industries",
    "Samsung SDS",
    "Louis Vuitton",
    "Dior",
    "Givenchy",
    "Sephora",
    "Bulgari",
    "Fendi",
    "Apple",
    "Google",
    "Vimeo",
    "Waymo",
    "DeepMind",
    "Pixel",
    "Facebook",
    "Messenger",
    "Threads",
    "Pringles",
    "Snickers",
    "Oreo",

    # ── §4.9 Casing variants ──────────────────────────────────────────────────
    "ACME TRADING CO.",
    "acme trading co",
    "Acme Trading CO",
    "Acme trading co.",
    "Ibm",
    "ibm",
    "IBM.",
    "IPhone",
    "iphone",
    "IPHONE",
    "Ebay",
    "EBAY",
    "ebay",
    "RELIANCE INDUSTRIES LIMITED",
    "reliance industries limited",
    "PROCTER AND GAMBLE",
    "procter and gamble",
    "SAMSUNG ELECTRONICS CO LTD",
    "samsung electronics",
    "HSBC BANK PLC",
    "hsbc bank",

    # ── §4.9 Suffix punctuation drift ────────────────────────────────────────
    "Riverside Manufacturing Inc",
    "Riverside Manufacturing INC",
    "Riverside Manufacturing Incorporated",
    "Hartfield & Sons Ltd,",
    "Hartfield & Sons LTD",
    "Hartfield & Sons Limited",
    "Wipro Pvt Ltd",
    "Wipro PVT LTD",
    "Wipro (P) Ltd.",
    "Wipro Pvt.Ltd.",
    "Wipro P. Ltd.",
    "Petronas Chemicals Sdn Bhd",
    "Petronas Chemicals Sdn.Bhd.",
    "Petronas Chemicals Sdn-Bhd",
    "Petronas Chemicals SDN BHD",
    "DBS Bank PTE LTD",
    "DBS Bank Pte. Ltd.",
    "DBS Bank Pte.Ltd",
    "Nordwind Logistics gmbh",
    "Nordwind Logistics GMBH",
    "Nordwind Logistics G.m.b.H.",
    "Cemex SA de CV",
    "Cemex S.A. de CV",
    "Cemex S.A.deC.V.",
    "Lyon Trading SA",
    "Compagnie Maritime de France S.A",
    "Compagnie Maritime de France S. A.",
    "Compagnie Maritime de France S/A",

    # ── §4.9 Whitespace / separator drift ────────────────────────────────────
    "Bristol Myers Squibb",
    "Bristol—Myers Squibb",
    "BristolMyers Squibb",
    "Mercedes Benz",
    "Mercedes-benz",
    "MercedesBenz",
    "Procter and Gamble",
    "Procter&Gamble",
    "Procter &Gamble",
    "Procter & gamble",
    "Coca Cola",
    "coca-cola",
    "CocaCola",
    "COCA-COLA",
    "H & M",
    "H and M",
    "h&m",
    "H AND M",
    "Haagen-Dazs",
    "Haagen Dazs",
    "HAAGEN-DAZS",
    "Häagen Dazs",
    "LOreal",
    "L'Oreal",
    "L Oreal",
    "Toys R Us",
    "Toys 'R' Us",
    "ToysRUs",

    # ── §4.9 Apostrophe variants (double-quoted) ──────────────────────────────
    "McDonalds",
    "Mcdonalds",
    "MCDONALD'S",
    "MCDONALDS",
    "McDonalds'",
    "O'Malley & Co.",
    "O Brien & Co.",
    "Sothebys",
    "SOTHEBYS",
    "Levis",
    "LEVIS",

    # ── §4.9 Abbreviation / acronym variants ─────────────────────────────────
    "International Business Machines Corporation",
    "Int'l Business Machines",
    "Internat'l Business Machines Corp.",
    "I.B.M.",
    "J.P. Morgan Chase & Co.",
    "JPMorgan Chase",
    "JP Morgan",
    "J.P.Morgan",
    "JPMorganChase",
    "JPM",
    "Bank of America Corporation",
    "BankAmerica",
    "BofA",
    "BoA",
    "B of A",
    "BAC",
    "Hewlett-Packard Company",
    "HP",
    "Hewlett Packard",
    "H-P",
    "HPE",
    "Hewlett-Packard Co.",
    "Standard Chartered Bank",
    "StanChart",
    "Standard Chartered",
    "SCB",
    "Standard Chartered plc",
    "Industrial and Commercial Bank of China",
    "Industrial & Commercial Bank",
    "Tata Consultancy Services Limited",
    "Tata Consultancy",

    # ── §4.9 Brand vs legal name ──────────────────────────────────────────────
    "Alphabet Inc.",
    "Google LLC",
    "Meta Platforms, Inc.",
    "Kellanova",
    "Kellogg Company",
    "Mars, Incorporated",
    "Frito-Lay, Inc.",
    "PepsiCo, Inc.",
    "Nestlé S.A.",
    "Mondelēz International",
    "Apple Inc.",

    # ── §4.9 OCR corruption ───────────────────────────────────────────────────
    "Acrne",
    "1BM",
    "lBM",
    "IBN",
    "IRM",
    "Pat agonia",
    "Pat-agonia",
    "Micro soft",
    "MicroSoft",
    "Microscft",
    "Sumltomo",
    "Sumttomo",
    "Haaqen-Dazs",
    "Aramoo",
    "Aramcc",
    "Lid",
    "Acme Tradi",

    # ── §4.9 Romanization / transliteration pairs ─────────────────────────────
    "China Petroleum & Chemical Corporation",
    "中国石油",
    "OAO Gazprom",
    "PJSC Gazprom",
    "Public Joint Stock Company Gazprom",
    "Gazprom",
    "Lukoil",
    "LUKOIL",
    "OOO Lukoil",
    "PAO Lukoil",
    "HUAWEI",
    "Samsung Display Co., Ltd.",
    "SEC",
    "Toyota Motor Corporation",
    "TMC",
    "Toyota Jidosha",
    "Hitachi, Ltd.",
    "Tata Group",
    "Tata Sons Pvt. Ltd.",
    "टाटा",
    "Mitsubishi Corporation",
    "Mitsubishi Shoji",
    "Reliance Industries",
    "रिलायंस",

    # ── §4.9 Subsidiary / branch / division (single ORG span) ────────────────
    "Acme Logistics (Singapore) Pte. Ltd.",
    "BNP Paribas Hong Kong Branch",
    "Mitsubishi Corporation (Americas)",
    "Acme Trading Asia-Pacific Pte. Ltd.",
    "Citi Private Bank, London",
    "Deutsche Bank AG, Frankfurt",
    "Standard Chartered Bank (Hong Kong) Limited",
    "HSBC India",
    "HSBC (UK)",
    "Barclays Capital Singapore",
    "JP Morgan Securities Japan",
    "Goldman Sachs India",
    "Citibank N.A., Mumbai Branch",
    "Deutsche Bank Trust Company Americas",
    "MUFG Bank, Ltd., London Branch",
    "Bank of China (Hong Kong) Limited",
    "Credit Suisse AG, Singapore Branch",
    "UBS AG Hong Kong",

    # ── §4.9 JV / DBA / trade-as patterns ────────────────────────────────────
    "Acme-XYZ Joint Venture",
    "Acme/XYZ JV",
    "Volkswagen-Audi Group Alliance",
    "Shell-Rosneft JV",
    "Shell-Chevron JV",
    "Acme Trading dba Speedy Logistics",
    "Acme Trading t/a Speedy Logistics",
    "Morrison & Clarke t/a MC Logistics",

    # ── §4.9 State-owned / national champions — long + short ──────────────────
    "China National Petroleum Corporation",
    "CNOOC Ltd",
    "Saudi Aramco Trading Company",
    "Saudi Aramco",
    "Petrobras",
    "Petrobras Distribuidora S.A.",
    "Pemex",
    "Petróleos Mexicanos",
    "Oil and Natural Gas Corporation Limited",
    "Bharat Electronics Limited",
    "Électricité de France",
    "Société nationale des chemins de fer français",
    "SNCF",
    "Korea Electric Power Corporation",
    "Equinor Energy AS",
    "Statoil",
    "Meta",
    "Facebook, Inc.",
    "Google Inc.",
    "Norsk Hydro",
    "Saudi Basic Industries Corporation",
    "SABIC",
    "Abu Dhabi National Oil Company",
    "ADNOC",
    "Coal India Limited",
    "National Iranian Oil Company",
    "NIOC",
    "Kuwait Petroleum Corporation",
    "KPC",
    "Iraq Petroleum Company",
    "Qatar General Electricity and Water Corporation",
    "Kahramaa",

    # ── §4.9 Bilingual / dual-script (one ORG span) ───────────────────────────
    "Mitsubishi 三菱",
    "Samsung 삼성電子",
    "中国移动 China Mobile",
    "HSBC 汇丰银行",
    "LVMH Moët Hennessy Louis Vuitton",
    "工商银行 ICBC",
    "Toyota トヨタ",
    "Huawei 华为",
    "Sinopec 中国石化",
    "Bank of China 中国银行",

    # ── §4.2 / §8.4 Suffix-less ORGs ────────────────────────────────────────
    "Acme Trading",
    "Oceanic Freight",
    "Pacific Rim Traders",
    "Atlantic Commodities",
    "Northern Star Resources",
    "Southern Cross Logistics",
    "Eastern Star Trading",
    "Western Pacific Imports",
    "Global Marine Services",
    "Continental Cargo",
    "Meridian Energy",
    "Apex Industrial",
    "Pinnacle Resources",
    "Quantum Freight",
    "Nexus Trading",
    "Horizon Commodities",
    "Alpha Logistics",
    "Beta Chemicals",
    "Delta Petroleum",
    "Gamma Industries",

    # ── §4.2 Compound with location ───────────────────────────────────────────
    "Bank of America",
    "Standard Chartered Singapore",
    "Bank of Tokyo",
    "Bank of China",
    "Bank of India",
    "Bank of England",
    "Gulf of Mexico Oil Company",
    "Amazon.com",
    "India Trade Corporation",
    "Africa Trading House",
    "Middle East Commodities",
    "Southeast Asia Freight",
    "Latin America Resources",
    "North Sea Energy",
    "Gulf Cooperation Industries",
    "Asia Pacific Holdings",
    "Trans-Siberian Rail Corporation",
    "Panama Canal Authority",
    "Suez Canal Authority",
    "Port of Rotterdam Authority",

    # ── §11.4 Regional traders ────────────────────────────────────────────────
    "Guangzhou Import & Export Co.",
    "Shenzhen Tech Trading Ltd",
    "Colombo Spice Traders",
    "Lagos Commodity Exchange",
    "Nairobi East Africa Traders",
    "Mumbai Textile Exporters",
    "Chennai Agri Commodities Pvt. Ltd.",
    "Dhaka Garment Industries Ltd.",
    "Karachi Port Logistics Pvt. Ltd.",
    "Manila Export Agency Inc.",
    "Jakarta Bulk Carriers Tbk",
    "Kuala Lumpur Agro Trade Sdn. Bhd.",
    "Bangkok Grain Traders Co., Ltd.",
    "Ho Chi Minh City Commodities JSC",
    "Casablanca Spice Négoce SA",
    "Alexandria Cotton Traders LLC",
    "Port Elizabeth Minerals Pty Ltd",
    "Santos Sugar Exporters Ltda.",
    "Buenos Aires Grain Trading S.A.",
    "Santiago Copper Traders SpA",

    # ── §11.4 SMEs ────────────────────────────────────────────────────────────
    "Greenfield Trading Co.",
    "Sunrise Exports Inc.",
    "Blue Horizon Importers LLC",
    "Silver Crest Logistics Pvt. Ltd.",
    "Golden Eagle Freight Sdn Bhd",
    "Red Maple Trading Ltd",
    "White Cloud Commodities BV",
    "Black Rock Resources GmbH",
    "Iron Gate Traders S.r.l.",
    "Stone Bridge Exporters S.A.",
    "River Valley Trading Co.",
    "Lake District Freight Ltd",
    "Mountain Pass Logistics",
    "Desert Rose Commodities",
    "Forest Glen Exports",
    "Ocean Breeze Trading",
    "Midland Bulk Carriers",
    "Highland Resources",
    "Lowland Commodities",
    "Coastal Star Logistics",

    # ── §11.4 Government / state-owned ───────────────────────────────────────
    "State Grid Corporation of China",
    "SGCC",
    "China State Construction Engineering Corporation",
    "CSCEC",
    "Korea National Oil Corporation",
    "KNOC",
    "Malaysian National Oil Corporation",
    "Petronas",
    "Brunei National Petroleum Company Sendirian Berhad",
    "PetroChina",
    "QatarEnergy",
    "National Oil Corporation of Libya",
    "Sonatrach",
    "Nigerian National Petroleum Corporation",
    "NNPC",
    "Ghana National Petroleum Corporation",
    "GNPC",
    "Tanzania Petroleum Development Corporation",
    "TPDC",
    "Ethiopian Electric Power",
    "Transnet SOC Ltd",

    # ── Additional global multinationals ─────────────────────────────────────
    "ExxonMobil Corporation",
    "Royal Dutch Shell",
    "Shell plc",
    "Chevron Corporation",
    "TotalEnergies SE",
    "ConocoPhillips",
    "Glencore plc",
    "Vitol Group",
    "Trafigura Group",
    "Cargill Incorporated",
    "ADM",
    "Archer Daniels Midland",
    "Bunge Limited",
    "Louis Dreyfus Company",
    "Noble Group",
    "Olam International",
    "Rio Tinto",
    "Vale International SA",
    "Freeport-McMoRan",
    "Anglo American",
    "Glencore",
    "Alcoa Corporation",
    "Norsk Hydro Aluminium AS",
    "BASF SE",
    "Dow Chemical Company",
    "DuPont de Nemours Inc.",
    "LyondellBasell Industries",
    "Sabic Innovative Plastics",
    "Toray Industries",
    "Asahi Kasei Corporation",
    "Formosa Chemicals & Fibre Corporation",
    "Reliance Petrochemicals",
    "Braskem S.A.",
    "Neste Oyj",
    "Repsol S.A.",
    "OMV AG",
    "Orlen S.A.",
    "PKN Orlen",
    "Hellenic Petroleum S.A.",
    "Tupras",
    "Indian Oil Corporation Limited",
    "Bharat Petroleum Corporation Limited",
    "Hindustan Petroleum Corporation Limited",
    "China National Offshore Oil Corporation",
    "Sinopec Shanghai Petrochemical Co., Ltd.",
    "PetroVietnam",
    "PTT Global Chemical PCL",
    "Formosa Plastics Corporation",
    "Nan Ya Plastics Corporation",
    "Far Eastern New Century Corporation",
    "Eternal Materials Co., Ltd.",

]
